### ISSUE TITLE
Package Name?

### ISSUE THREAD

**Issue by donggyukim** [ucb-bar/chisel-testers#9]
Is there any problem with Chisel.testers._ ?

**Comment by sdtwigg** [comment]
As per https://github.com/ucb-bar/chisel3/pull/197, chisel.testers better conforms to Scala style.

(tester vs testers is a tempting argument but the repo is called chisel-testers so that kinda settles that argument.) It is organizationall weird that the chisel3 repo already injects some stuff into the chisel.testers package but not technically a problem.
